server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / { try_files $uri $uri/ /index.html; }

    location /api/node/ {
        proxy_pass http://node-api:3001/;
        proxy_set_header Host $host;
    }
    location /api/python/ {
        proxy_pass http://python-api:8001/;
        proxy_set_header Host $host;
    }
}
